apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-go-rhtap-three-component-scenarios-pomn
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-lfjp-tenant/mc-three-scenarios/devfile-go-rhtap-three-component-scenarios-pomn@sha256:d801ae582da43c7f734191819be43e09509c97e46f9666d4864131f8ee9b2bef
        name: my-go
        resources: {}
status: {}
